# App name
spring.application.name=our-restaurant-backend

# Server port
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/our_restaurant
spring.datasource.username=root
spring.datasource.password=Patil@96k
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Allow frontend to connect
spring.web.cors.allowed-origins=*